apiVersion: v1
data:
  token: MC5mNzg1ZTYxZC1hY2M5LTQ5MTYtYWJiNi1iM2I5MDA4Mzk0NDkuTTIwTVlpNzVRQ0NJVlFWbEhCOVMyZ1RIQnJWNTVVOnlNTGNXUmdvSEh4SjhwSzEzaWw5NFE9PQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: bw-auth-token
