apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ipv4-pool
spec:
  addresses:
    - 192.168.1.221-192.168.1.230
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-dual-stack-pool
spec:
  addresses:
    - 192.168.1.200-192.168.1.220
    - 2001:14ba:700e:0c00:1144:dcf2:fdb9:b676-2001:14ba:700e:0c00:1144:dcf2:fdb9:b67f
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-ip-advertisement
