apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: cloudflare
spec:
  organizationId: "60ceb718-168e-4c92-acbc-b2dc012f1217"
  secretName: cloudflare
  map:
    - bwSecretId: "d5a7351c-a839-49f5-a67f-b2dc0131528b"
      secretKeyName: api-key
  authToken:
    secretName: bw-auth-token
    secretKey: token
