apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: traefik-basic-auth
spec:
  organizationId: "60ceb718-168e-4c92-acbc-b2dc012f1217"
  secretName: traefik-basic-auth   # <- the k8s Secret Traefik will read
  onlyMappedSecrets: true
  map:
    - bwSecretId: "737269fb-cd4b-4a9d-a47d-b3b2017c5080"
      secretKeyName: "users"       # <- must be 'users' for basicAuth
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-auth
spec:
  basicAuth:
    secret: traefik-basic-auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-allowlan
spec:
  ipAllowList:
    sourceRange:
      - 192.168.1.0/24
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-slash
spec:
  redirectRegex:
    regex: ^(.*)/dashboard$
    replacement: ${1}/dashboard/
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-root-redirect
spec:
  redirectRegex:
    regex: ^https?://[^/]+/?$
    replacement: /dashboard/
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.k8s.karkki.org`)
      kind: Rule
      middlewares:
        - name: traefik-dashboard-auth
        - name: traefik-dashboard-slash
        - name: traefik-dashboard-root-redirect
      services:
        - name: api@internal
          kind: TraefikService
