apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: cloudflare
spec:
  organizationId: "60ceb718-168e-4c92-acbc-b2dc012f1217"
  secretName: cloudflare # pragma: allowlist secret
  map:
    - bwSecretId: "08393544-bffb-420d-9aa5-b2dc01315f21"
      secretKeyName: api-token # pragma: allowlist secret
    - bwSecretId: "9cbb5a9b-0a89-4ab9-9cac-b2dc013170da"
      secretKeyName: domain # pragma: allowlist secret
  authToken:
    secretName: bw-auth-token # pragma: allowlist secret
    secretKey: token # pragma: allowlist secret
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: favonia/cloudflare-ddns:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: CLOUDFLARE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare
                      key: api-token
                - name: DOMAINS
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare
                      key: domain
                - name: PROXIED
                  value: "false"
                - name: UPDATE_CRON
                  value: "@once"
                - name: UPDATE_ON_START
                  value: "true"
                - name: IP6_PROVIDER
                  value: "none"  # Optional: disable IPv6 if not needed
          restartPolicy: Never
